### ISSUE TITLE
README / docs ?

### ISSUE THREAD

**Issue by kitsunet** [Flowpack/neos-dimensionresolver#7]
Would be nice ;)

**Comment by bwaidelich** [comment]
They are here: https://github.com/Flowpack/neos-dimensionresolver/blob/master/Documentation/index.rst

but I would suggest to move that to `/README.md` so that it's more visible

**Comment by crydotsnake** [comment]
> They are here: https://github.com/Flowpack/neos-dimensionresolver/blob/master/Documentation/index.rst
> 
> but I would suggest to move that to `/README.md` so that it's more visible


Will take care
